### ISSUE TITLE
Error when generating coverage report on some Vue files with import

### ISSUE THREAD

**Issue by azamat-sharapov** [cenfun/monocart-reporter#54]
I'm trying to generate coverage report for Vue files using Playwright Component Testing. It was working fine until recent updates. When a Vue file has imports from `@heroicons/vue` package, e.g. `import { ChevronDownIcon } from '@heroicons/vue/20/solid'`, I get following error. When I remove that import, there is no error.

```
[MCR] loaded 6 sourcemaps (80 ms)

  1 passed (5.3s)
[MCR] generating report data ...
[MCR] generating global coverage report ...
[MCR] decode source mappings assets/index-caf6d1d3.js (189 ms)
[MCR] decode source mappings VerticalNavMobile-54b3351d.js (76 ms)
[MCR] decode source mappings vue.runtime.esm-bundler-bcfba368.js (76 ms)
Error in reporter TypeError: Cannot read properties of undefined (reading 'generatedOffset')
    at findMapping (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/find-original-range.js:20:26)
    at findOffsetMapping (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/find-original-range.js:31:21)
    at findStartMapping (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/find-original-range.js:432:26)
    at findOriginalRange (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/find-original-range.js:512:25)
    at /Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/converter.js:420:28
    at Array.forEach (<anonymous>)
    at /Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/converter.js:418:22
    at Array.forEach (<anonymous>)
    at unpackSourceMap (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/converter.js:417:20)
    at unpackDistFile (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/converter.js:477:9)
    at convertV8List (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/converter/converter.js:536:9)
    at getGlobalCoverageData (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/coverage.js:236:43)
    at generateGlobalCoverageReport (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/plugins/coverage/coverage.js:279:20)
    at artifactsHandler (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/generate-data.js:23:24)
    at generateData (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/generate-data.js:83:23)
    at Reporter.onEnd (/Users/admin/code/web-app/frontend/node_modules/.pnpm/monocart-reporter@1.7.3/node_modules/monocart-reporter/lib/index.js:198:28)
    at wrapAsync (/Users/admin/code/web-app/frontend/node_modules/.pnpm/@playwright+test@1.35.1/node_modules/@playwright/test/lib/reporters/multiplexer.js:92:5)
    at Multiplexer.onEnd (/Users/admin/code/web-app/frontend/node_modules/.pnpm/@playwright+test@1.35.1/node_modules/@playwright/test/lib/reporters/multiplexer.js:59:45)
    at InternalReporter.onExit (/Users/admin/code/web-app/frontend/node_modules/.pnpm/@playwright+test@1.35.1/node_modules/@playwright/test/lib/reporters/internalReporter.js:94:5)
    at Runner.runAllTests (/Users/admin/code/web-app/frontend/node_modules/.pnpm/@playwright+test@1.35.1/node_modules/@playwright/test/lib/runner/runner.js:78:5)
    at runTests (/Users/admin/code/web-app/frontend/node_modules/.pnpm/@playwright+test@1.35.1/node_modules/@playwright/test/lib/cli.js:132:93)
    at qr.<anonymous> (/Users/admin/code/web-app/frontend/node_modules/.pnpm/@playwright+test@1.35.1/node_modules/@playwright/test/lib/cli.js:40:7)
```

**Comment by cenfun** [comment]
let me check, thanks

**Comment by cenfun** [comment]
Unfortunately, I can not reproduce it with following
```
import { ChevronDownIcon } from '@heroicons/vue/20/solid'
```
can you create a minimal demo that reproduces the issue?

**Comment by cenfun** [comment]
can you try monocart-reporter@1.7.4, there is a quick fix with following, please try and see if the issue still exists?
![image](https://github.com/cenfun/monocart-reporter/assets/334577/f18b6a78-9bda-4494-ac28-22bc5a715786)

**Comment by azamat-sharapov** [comment]
@cenfun thanks for the quick fix! It's working now 👍🏻
