### ISSUE TITLE
v2.1.0 Error in reporter TypeError

### ISSUE THREAD

**Issue by jiadesen** [cenfun/monocart-reporter#85]
When there are failed cases:

```
[MR] generating report data ...
Error in reporter TypeError: Cannot read properties of undefined (reading 'startOffset')
    at quickFindRange (/Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/converter/branches.js:21:28)
    at findInRanges (/Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/converter/branches.js:29:19)
    at /Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/converter/ast.js:247:34
    at Array.forEach (<anonymous>)
    at addCssRules (/Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/converter/ast.js:199:11)
    at getCssAstInfo (/Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/converter/ast.js:286:5)
    at convertV8List (/Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/converter/converter.js:991:23)
    at generateCoverageReports (/Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/generate.js:135:47)
    at CoverageReport.generate (/Users/xxx/node_modules/.pnpm/monocart-coverage-reports@2.0.0/node_modules/monocart-coverage-reports/lib/index.js:106:33)
    at generateGlobalCoverageReport (/Users/xxx/node_modules/.pnpm/monocart-reporter@2.1.0/node_modules/monocart-reporter/lib/plugins/coverage/coverage.js:96:29)
    at artifactsHandler (/Users/xxx/node_modules/.pnpm/monocart-reporter@2.1.0/node_modules/monocart-reporter/lib/generate-data.js:22:34)
    at generateData (/Users/xxx/node_modules/.pnpm/monocart-reporter@2.1.0/node_modules/monocart-reporter/lib/generate-data.js:90:23)
    at Reporter.onEnd (/Users/xxx/node_modules/.pnpm/monocart-reporter@2.1.0/node_modules/monocart-reporter/lib/index.js:203:28)
    at ReporterV2Wrapper.onEnd (/Users/xxx/node_modules/.pnpm/playwright@1.40.1/node_modules/playwright/lib/reporters/reporterV2.js:91:12)
    at wrapAsync (/Users/xxx/node_modules/.pnpm/playwright@1.40.1/node_modules/playwright/lib/reporters/multiplexer.js:79:12)
    at Multiplexer.onEnd (/Users/xxx/node_modules/.pnpm/playwright@1.40.1/node_modules/playwright/lib/reporters/multiplexer.js:51:25)
    at InternalReporter.onEnd (/Users/xxx/node_modules/.pnpm/playwright@1.40.1/node_modules/playwright/lib/reporters/internalReporter.js:69:12)
    at Runner.runAllTests (/Users/xxx/node_modules/.pnpm/playwright@1.40.1/node_modules/playwright/lib/runner/runner.js:77:28)
    at runTests (/Users/xxx/node_modules/.pnpm/playwright@1.40.1/node_modules/playwright/lib/cli.js:130:93)
    at t.<anonymous> (/Users/xxx/node_modules/.pnpm/playwright@1.40.1/node_modules/playwright/lib/cli.js:40:7)
```

**Comment by jiadesen** [comment]
v2.0.4 has been working very well

**Comment by cenfun** [comment]
just release a new version monocart-coverage-reports@2.0.1 to fix the error.
please try reinstall the node modules
1, goto node_modules dir and remove folder `monocart-coverage-reports`
2, reinstall again and make sure monocart-coverage-reports@2.0.1 installed

**Comment by jiadesen** [comment]
It has been solved, thank you very much!!!
